### ISSUE TITLE
未能找到请求的值“LongCT”

### ISSUE THREAD

**Issue by yangmail2002** [robinli/MVC5-Scaffolder#1]
我引用了，以下代码，出现的错误为：
    运行所选代码生成器时出错：
   未能找到请求的值“LongCT”

我的类定义如下：
 public class BCChangeHistoriesDto : YZ.GenericComponent.Model.Core.AuditableDto
    {
        /// <summary>

        /// 记录号
        /// </summary>

        [Key]
        public long Id { get; set; }
        /// <summary>

        /// 卡物理卡
        /// </summary>

 
        public string MangeIDUserId { get; set; }
        /// <summary>

        /// 卡显示号
        /// </summary>

        [Required]
        [StringLength(128)]
        public string  CardIDUserName { get; set; }
        /// <summary>

        /// 变动数量
        /// </summary>

        public Nullable<decimal> ChangeValue { get; set; }
        /// <summary>

        ///本条记录记录的数据类型 帐号金额变动 = 0,卡金额变动 = 1,其它操作 = 2
        /// </summary>

        public Nullable<DtoRecordContextObjectTypes> RecordContextObject { get; set; }
        /// <summary>

        ///  充值 = 0,转帐 = 1,消费 = 2,开启 = 3,挂失 = 4,绑定 = 5
        /// </summary>

        public Nullable<DtoBalacneChangesOperationses> Operations { get; set; }
        /// <summary>

        /// 帐户金额变动，资金变动的来源 银联 = 0,   银行卡 = 1, 支付宝 = 2, 贝宝 = 3,  充值卡 = 6,  帐号 = 7 等
        /// </summary>

        public Nullable<DtoCapitalSources> CapitalSource { get; set; }
        /// <summary>

        /// 描述
        /// </summary>

        public string Description { get; set; }
        /// <summary>

        /// 绑定帐号
        /// </summary>

        public string CardBoundUser { get; set; }
        /// <summary>

        /// 绑定帐号名称
        /// </summary>

        public string BoundUserName { get; set; }
        /// <summary>

        /// 操作商店
        /// </summary>

        public string ShopId { get; set; }
        /// <summary>

        /// 操作设备
        /// </summary>

        public string DeviceID { get; set; }
        /// <summary>

        /// 赠送金额
        /// </summary>

        public Nullable<decimal> PresentMoney { get; set; }
        /// <summary>

        /// 返回主建
        /// </summary>

        public override object[] Keys
        {
            get { return new object[] { Id }; }
        }
    }

 // 摘要: 
    //     输出视图的基类，完成公共属性的设置
    [Serializable]
    public abstract class AuditableDto : EntityBase
    {
 // 摘要: 
        //     获取或设置 添加时间
        [DataType(DataType.DateTime)]
        [Display(Name = "创建时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        public virtual DateTime? CreateDate { get; set; }
        //
        // 摘要: 
        //     增加记录的用户
        [Display(Name = "创建用户号")]
        public virtual string CreateUserId { get; set; }
        //
        // 摘要: 
        //     增加记录的用户
        [Display(Name = "创建用户名")]
        public virtual string CreateUserName { get; set; }
        //
        // 摘要: 
        //     获取或设置 ，逻辑上的删除，非物理删除
        [Display(Name = "逻辑删除")]
        public virtual bool? DeleteMark { get; set; }
        //
        // 摘要: 
        //     获取或设置 ，记录是否显示出来
        [Display(Name = "是否显示")]
        public virtual bool? DisplayMark { get; set; }
        //
        // 摘要: 
        //     最近更新记录的时间
        [DataType(DataType.DateTime)]
        [Display(Name = "最近更新记录的时间")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        public virtual DateTime? ModifyDate { get; set; }
        //
        // 摘要: 
        //     最后更新记录的用户
        [Display(Name = "最近更新记录的用户号")]
        public virtual string ModifyUserId { get; set; }
        //
        // 摘要: 
        //     最后更新记录的用户名
        [Display(Name = "最近更新记录的用户名")]
        public virtual string ModifyUserName { get; set; }
        //
        // 摘要: 
        //     获取或设置是否禁用
        [Display(Name = "记录的状态")]
        [EnumDataType(typeof(RecordStatuses))]
        public virtual RecordStatuses? RecordStatus { get; set; }
        //
        // 摘要: 
        //     获取或设置 ，记录是显示的顺序,也叫排序码
        [Display(Name = "排序（降序排序）")]
        public virtual int? SortCode { get; set; }
｝

**Comment by robinli** [comment]
已新增資料型別 long 的列舉，Models\euColumnType.cs
