### ISSUE TITLE
Visual Studio 2015

### ISSUE THREAD

**Issue by emersonmellado** [robinli/MVC5-Scaffolder#3]
Any chance to make a version for Visual Studio 2015?

Thanks.

**Comment by shinjiDev** [comment]
Is it still supported? Or does anyone know any fork with VS2015 support?

**Comment by robinli** [comment]
I just changed it, can install target on VS2015 now.

**Comment by emersonmellado** [comment]
Thank you Robin!! Awesome job, by the way.
